AWSTemplateFormatVersion: '2010-09-09'
Description: 'Plantilla per desplegar una web estatica amb S3 - Classe DevOps'

# NOU: Definim un paràmetre que l'alumne haurà d'omplir
Parameters:
  NomAlumne:
    Type: String
    Description: 'Escriu el teu nom o cognom (en minúscules i sense accents) per fer el bucket únic.'
    MinLength: 3
    MaxLength: 20
    AllowedPattern: '[a-z0-9\-]+'
    ConstraintDescription: 'Només minúscules, números i guions.'

Resources:
  # 1. El Bucket de S3 on viurà la web
  BucketWebClasse:
    Type: 'AWS::S3::Bucket'
    Properties:
      # MODIFICAT: Fem servir el paràmetre per crear un nom únic
      BucketName: !Sub 'web-classe-devops-${NomAlumne}-2024'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # 2. Política per permetre que tothom llegeixi els fitxers de la web
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref BucketWebClasse
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${BucketWebClasse.Arn}/*'

  # 3. El fitxer HTML que pugem al bucket
  FitxerIndex:
    Type: 'AWS::S3::Object'
    Properties:
      Target:
        Bucket: !Ref BucketWebClasse
        Key: 'index.html'
      Source: 'SourceArtifact/index.html'
      ContentType: 'text/html'

Outputs:
  URLWeb:
    Description: 'URL de la web desplegada'
    Value: !GetAtt BucketWebClasse.WebsiteURL
